### PR TITLE
Free allocated memory of linked list

### PR DESCRIPTION
**Pull request by furuame**

### CODE REVIEW

**Comment by Lukechin** [comment]
Can I rename your function from freeList to free?

**Comment by furuame** [comment]
It will be duplicated with free() in stdlib

**Comment by Lukechin** [comment]
OK, I see.

**Comment by furuame** [comment]
What name do you prefer?

**Comment by Lukechin** [comment]
I think freeList() is OK if it will be duplicated with free(). 
I haven't thought any other better name yet. 
I will merge your PR later. Thanks a lot

**Comment by jserv** [comment]
Rebase to get rip of `Merge branch 'master' into task/free_list_memory`.

**Comment by furuame** [comment]
Okay, I will get rip of this commit.

**Pull request closed without merging**
